### ISSUE TITLE
Google Verification Issue

### ISSUE THREAD

**Issue by GingerK674** [bobbingwide/genesis-SB#20]
I installed Yoast plug-in on my live and staging sites. I verified the staging site with my HTML code under the Yoast webmaster tools area. Now, when I push my staging site live, the staging URL's appear on all my live site pages, except for the HOME page. I deleted the verification code from both Yoast plugins and deactivated both plug-ins. The problem still occurs. When I go to Google console, I do not see my staging site listed as a property. Any suggestions would be appreciated.

**Comment by bobbingwide** [comment]
@GingerK674 Can you explain what this has to do with the Genesis-SB theme?

**Comment by GingerK674** [comment]
I didn't realize requests had to relate directly to Genesis. You can ignore, I've reached out to a developer for assistance.

**Comment by bobbingwide** [comment]
Well, this repository is actually a child theme of Genesis. Good like with resolving your problem. 
I'm going to close the issue as wontfix. but won't delete it.
